# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - simplemlops1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://simpleapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d0377646352458cbfd257d19ac46783 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d1a79c03972b44549c717479da0e7c30 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: simpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d0377646352458cbfd257d19ac46783 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'simplemlops1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1310372a2f88421fa8f3a9b82036ea47 }}
        images: 'simpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d0377646352458cbfd257d19ac46783 }}/mltest:${{ github.sha }}'