# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - simplemlops

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://simpleapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dbc41e534924423cb04d6b258b749454 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3fd104e3df34fcfa5527c8e575a802c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: simpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dbc41e534924423cb04d6b258b749454 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'simplemlops'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3bbfed3ea00e47d7b1abd50104d1e3ad }}
        images: 'simpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dbc41e534924423cb04d6b258b749454 }}/mltest:${{ github.sha }}'